spring:
  application:
    name: petrochem
  config:
    use-legacy-processing: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    suffix: .html
    cache: false
    check-template-location: true

server:
  port: 9922
  servlet:
    context-path: /
    session:
      timeout: 86400
      tracking-modes: cookie
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-stacktrace: always
    path: /common/error

logging:
  config: classpath:logback-spring.xml

---

spring:
  config:
    activate:
      on-profile: localhost
  datasource:
    hikari:
      #jdbc-url: jdbc:p6spy:mariadb://10.0.0.4:13306/management #터널링
      jdbc-url: jdbc:p6spy:mariadb://20.196.152.131:3306/management #운영
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      username: ptg0131
      password: "3828"
      pool-name: pool-
      auto-commit: false
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED

mybatis:
  configuration:
    map-underscore-to-camel-case: true
